### PR TITLE
#150749927 cancel order option

### PR DESCRIPTION
**Pull request by Jchinonso**
#### What does this PR do?
- Add a cancel order button  
#### Description of Task to be completed?
- Give Buyer option to cancel order after order is made
#### How should this be manually tested?
- Nill
#### Any background context you want to provide?
- Nill 
#### What are the relevant pivotal tracker stories?
- #150749927
#### Screenshots (if appropriate)
image
image
image

#### Questions:
- Nill

### CODE REVIEW

**Comment by temilaj** [comment]
I'm curious to know why you avoided documenting most of the methods in this PR?

**Comment by Jchinonso** [comment]
jsdoc was just not adapted to auto-doc with Meteor's implementation

**Comment by Jchinonso** [comment]
But i will add jsdoc in the react part

**Comment by temilaj** [comment]
"jsdoc was just not adapted to auto-doc with Meteor's implementation" Are you implying that you won't write documentation for your codebase if there isn't any auto-implementation for it?

**Comment by Jchinonso** [comment]
initially i was confuse on why its so, but i discovered a different module meteor-jsdoc

**Comment by temilaj** [comment]
Please resolve the conflicts and raise another PR

**Pull request closed without merging**
